### PR TITLE
support async workflows

### PR DESCRIPTION
**Pull request by mafintosh**
been wanting to integrate something with slack that needs async stuff. could be misunderstanding the module but here is a pr that makes that work (breaking change)

### CODE REVIEW

**Comment by freeall** [comment]
@mafintosh what's the specific use case for this?

**Comment by mafintosh** [comment]
For Dat I want to port my IRC bot to slack as well. 

I mention the bot with a dat link. It saves it to leveldb and starts replicating it. If it fails for whatever reason I want the webhook to retrigger

**Comment by mafintosh** [comment]
If this module is a bad use case for that, feel free to close this PR :)

**Comment by freeall** [comment]
But does it change anything if it's a callback or an event emitter in that regard? Just trying to understand it.

**Comment by mafintosh** [comment]
@freeall yea. its async so if it fails i wanna return an error to slack so they retry the hook. can't do that with the eventemitter since it is sync.

**Comment by freeall** [comment]
gotcha

**Comment by joshuakarjala** [comment]
@mafintosh ah ok

Slack recommends responding right away on reception to avoid delays.
https://api.slack.com/events-api#receiving_events

> De-couple your ingestion of events from processing and reacting to them. Especially when working with large teams, many teams, or subscribing to a large number of events. Quickly respond to events with HTTP 200 and add them to a queue before doing amazing things with them.

Depending on use case / scale it is probably reasonable to be able to reply in 3 seconds even if doing some processing.

> Your app should respond to the event request with an HTTP 2xx within three seconds. If it does not, we'll consider the event delivery attempt failed. After a failure, we'll retry three times, backing off exponentially.

**Comment by mafintosh** [comment]
Makes sense. To add it to a queue I still need the async support though.

**Comment by freeall** [comment]
@mafintosh check now https://github.com/FoundersAS/express-slack-events-listener/blob/master/index.js

**Comment by joshuakarjala** [comment]
@mafintosh 

https://github.com/FoundersAS/express-slack-events-listener

**Comment by mafintosh** [comment]
@freeall @joshuakarjala thats still sync or am i missing something?

**Comment by freeall** [comment]
@mafintosh which part is sync?

**Comment by mafintosh** [comment]
@freeall
https://github.com/FoundersAS/express-slack-events-listener/blob/master/index.js#L16

**Comment by joshuakarjala** [comment]
@mafintosh now not sync

**Pull request closed without merging**
